version: '3.3'

networks:
  subido:

services:
  subido:
    image: subido:latest
    hostname: subido
    container_name: subido
  ports:
      - "18080:8080"
      - "18081:8081"
    networks:
      - subido
